### ISSUE TITLE
Support for smtp_tls_security_level and smtpd_tls_security_level

### ISSUE THREAD

**Issue by AndyFux** [Oefenweb/ansible-postfix#124]
Hi,

i cannot configure either smtp_tls_security_level nor smtpd_tls_security_level.

Currently i'm usng the raw_options:

postfix_raw_options:
  - smtp_tls_security_level = may
  - smtpd_tls_security_level = may

Is possible to support the options?

Greetings Andy

**Comment by tersmitten** [comment]
Sure, feel free to open an PR

**Comment by tersmitten** [comment]
Make sure to have a look at #117 and #127

**Comment by tersmitten** [comment]
I think that both are supported now
