### ISSUE TITLE
postfix_virtual_aliases_type

### ISSUE THREAD

**Issue by logiczny** [Oefenweb/ansible-postfix#125]
Hi,
would you like to add an option to specify a type of virtual alias map?
By default, it's assumes hash, by If I want to specify regexp, it's ignored.
`postfix_virtual_aliases_type: regexp`

**Comment by tersmitten** [comment]
Feel free to create a PR

**Comment by logiczny** [comment]
By this point I simply don't remember why I needed that nor I need that. I'll close it. Thanks for your work! :)
