### ISSUE TITLE
3.7.0 not available on galaxy

### ISSUE THREAD

**Issue by dnrce** [Oefenweb/ansible-postfix#139]
The latest release v3.7.0 is not available on Ansible Galaxy: https://galaxy.ansible.com/ui/standalone/roles/Oefenweb/postfix/versions/

FWIW, the CI release action appears to have succeeded: https://github.com/Oefenweb/ansible-postfix/actions/runs/8433750367 🤷

**Comment by tersmitten** [comment]
Fixed it, should auto update from now on (again)
