### ISSUE TITLE
Postfix generic table support

### ISSUE THREAD

**Issue by ericschaetzlein** [Oefenweb/ansible-postfix#38]
Hi Mischa,

I need the /etc/postfix/generic table mapping for our setup.
(see http://www.postfix.org/generic.5.html)

I did all the necessary adaptions, but of course I'd love those to be included in the main branch.

I'm sorry I never done that before, are you considering this and if so, how can I provide you with the adaptions?

Thanks and all the best,
Eric

**Comment by tersmitten** [comment]
Hi Eric,

Feel free to open a pull request. If it does not break existing installations and adds a new feature I don't see any reason not to incorporate it.

Regards, Mischa

**Comment by ericschaetzlein** [comment]
Done :)
Shouldn't break anything since the default setting is [], meaning don't create a generic table.

**Comment by tersmitten** [comment]
Fixed in #39

**Comment by ericschaetzlein** [comment]
Thanks! :)
