### ISSUE TITLE
Sasl authentication problem

### ISSUE THREAD

**Issue by dsteinkopf** [Oefenweb/ansible-postfix#45]
After updating to current version 2.4.0 my postfix didn't correctly authenticate to its relayhost.
The reason seems to be this line in aa3a416:
`postfix_sasl_mechanism_filter: plain`

I got this error message in `mail.log`:
```
relay=a.b.c[x.x.x.x]:25, delay=151584, delays=151578/0.02/6.2/0, dsn=4.7.0, status=deferred (SASL authentication failed: server a.b.c[x.x.x.x] offered no compatible authentication mechanisms for this type of connection security)
```

Setting `postfix_sasl_mechanism_filter: # empty` in my playbook solved the problem.

Is it really a good idea to set `plain` as default value for `postfix_sasl_mechanism_filter`?
I'd suggest empty value as default as this is also postfix' default.

**Comment by tersmitten** [comment]
@dennisse

**Comment by tersmitten** [comment]
I think you're right. Can you make a PR?

**Comment by dennisse** [comment]
Oh wow, of course empty is a better default. Sorry about that :)
