### ISSUE TITLE
ansible-postfix not found on Ansible Galaxy

### ISSUE THREAD

**Issue by juangallostra** [Oefenweb/ansible-postfix#47]
## Steps to reproduce
Either try to download the role from [Ansible Galaxy](https://galaxy.ansible.com/home), which raises the error:
```
[WARNING]: - tersmitten.postfix was NOT installed successfully: - sorry,
tersmitten.postfix was not found on https://galaxy.ansible.com.
```
or navigate to https://galaxy.ansible.com/tersmitten/postfix

## Expected behaviour

ansible-postfix role can be downloaded from [Ansible Galaxy](https://galaxy.ansible.com/home)

**Comment by tersmitten** [comment]
See https://github.com/Oefenweb/ansible-locales/issues/11

**Comment by tersmitten** [comment]
Feel free to fix the `README`. Thanks in advance
