### ISSUE TITLE
smtpd_recipient_restrictions = permit_sasl_authenticated,permit_mynetworks,reject_unauth_destination

### ISSUE THREAD

**Issue by oggers** [Oefenweb/ansible-postfix#49]
I have a relayhost configured and when I start postfix I get this error in mail.err:

`Jul 17 16:13:25 luna postfix/smtpd[30323]: fatal: in parameter smtpd_relay_restrictions or smtpd_recipient_restrictions, specify at least one working instance of: reject_unauth_destination, defer_unauth_destination, reject, defer, defer_if_permit or check_relay_domains`

After manually adding to main.cf at least:
`smtpd_relay_restrictions = permit_sasl_authenticated,reject_unauth_destination
`
the error went away.

Could you please add this option?

**Comment by tersmitten** [comment]
Can you make a pull request?

You might want to have a look at `postfix_mydestination` and only print it if it's a non-empty list

**Comment by tersmitten** [comment]
Fixed in #50
