### ISSUE TITLE
inet_protocols and inet_interfaces added with parenthesis:

### ISSUE THREAD

**Issue by hakkyou** [Oefenweb/ansible-postfix#60]
Input:
```
  vars:
    postfix_inet_interfaces:
     - 'loopback-only'
```

Expected behaviour:
in /etc/postfix/main.cf:
```
inet_interfaces = loopback-only
inet_protocols = ipv4
```

Actual behaviour:
in /etc/postfix/main.cf:
```
inet_interfaces = ['loopback-only']
inet_protocols = ['ipv4']
```

**Comment by tersmitten** [comment]
I don't think this is really a bug, `inet_interfaces` and `inet_protocols` are both string variable, so you need to provide a string value:

```yml
  vars:
    postfix_inet_interfaces: loopback-only
```

However it's probably better to make both of `list` type, but that's not backwards compatible :-( Can you you propose a backwards compatible fix?

**Comment by tersmitten** [comment]
http://www.postfix.org/postconf.5.html#inet_interfaces
