### ISSUE TITLE
anything entry

### ISSUE THREAD

**Issue by MichaelMichaelMichaelMichaelMichael** [Oefenweb/ansible-postfix#65]
When creating entries in the virtual file, shouldn't those entries have a 'virtual-alias.domain anything' entry per virtual-alias.domain? The postfix virtual man page says:

>       The virtual-alias.domain anything entry is required for a virtual alias
>       domain.  Without  this  entry,  mail  is  rejected  with  "relay access
>       denied", or bounces with "mail loops back to myself".

**Comment by tersmitten** [comment]
Is this still relevant?

**Comment by tersmitten** [comment]
@MichaelMichaelMichaelMichaelMichael
