### ISSUE TITLE
postfix_*_canonical_maps_file variables incorrect

### ISSUE THREAD

**Issue by pichogve** [Oefenweb/ansible-postfix#67]
Are the values of variables postfix_sender_canonical_maps_file and postfix_recipient_canonical_maps_file swapped in vars/main.yml?

Right now they look like this:

`
postfix_sender_canonical_maps_file: /etc/postfix/recipient_canonical_maps
postfix_recipient_canonical_maps_file: /etc/postfix/sender_canonical_maps
`

Should it be like this instead?

`
postfix_sender_canonical_maps_file: /etc/postfix/sender_canonical_maps
postfix_recipient_canonical_maps_file: /etc/postfix/recipient_canonical_maps
`

**Comment by tersmitten** [comment]
Still relevant?

**Comment by tersmitten** [comment]
Or fixed by #68

**Comment by tersmitten** [comment]
Checked it. It's fine the way it is now
