### ISSUE TITLE
Publish 2.8.5 to Ansible Galaxy?

### ISSUE THREAD

**Issue by adborden** [Oefenweb/ansible-postfix#72]
Hello, thanks for creating a tag for 2.8.5! Would you please publish it to galaxy.ansible.com so that folks can more easily download it?

**Comment by tersmitten** [comment]
I should auto-update. `2.8.5` should be there:

https://galaxy.ansible.com/oefenweb/postfix

**Comment by adborden** [comment]
Thanks!
