### ISSUE TITLE
/etc/aliases is not updated when an entry is remove from {{ postfix_aliases }}

### ISSUE THREAD

**Issue by astraios** [Oefenweb/ansible-postfix#78]
Because /etc/aliases is managed in with the lineinfile module and a loop, the playbook has no way to know when an item has been removed. If no changes is detected on the other lines, the "new aliases" handler is not fired.

Maybe it could be possible to use a template instead ?

Role version is : v2.9.1

**Comment by agimenez** [comment]
Hey @astraios, I just submitted a PR to fix this.

@tersmitten care to take a look? Thanks!
