### ISSUE TITLE
Encrypt outgoing messages with STARTTLS

### ISSUE THREAD

**Issue by theel0ja** [Oefenweb/ansible-postfix#79]
Currently STARTTLS for outgoing email is not enabled, as seen in headers of an email sent by a Postfix server configured by `ansible-postfix`:

```
Received: from ansible-postfix-server (ansible-postfix-server [IPv6:redacted])
	by mail.redacted with ESMTP
	for <redacted>;
```

Default should be:

```
smtp_tls_security_level = may
```

Read more: http://www.postfix.org/postconf.5.html#smtp_tls_security_level

**Comment by tersmitten** [comment]
Can you make a pull request?
