### ISSUE TITLE
/etc/aliases is not compatible with regexp database type

### ISSUE THREAD

**Issue by adborden** [Oefenweb/ansible-postfix#88]
If I run the playbook with `postfix_default_database_type: regexp` and no aliases configured. I see this warning in the postfix logs:

```
postfix/local[25233]: warning: regexp map /etc/aliases, line 1: ignoring unrecognized request
```

It looks like even though database type is set to `regexp`, /etc/aliases still contains `postmaster:root` as if it was a hash table.

**Comment by tersmitten** [comment]
Fixed in https://github.com/Oefenweb/ansible-postfix/releases/tag/v3.2.1
