### ISSUE TITLE
set postfix_smtpd_relay_restrictions to default postfix value

### ISSUE THREAD

**Issue by manelclos** [Oefenweb/ansible-postfix#97]
Hi,

After using this role with ubuntu-focal:

mail.log:
```
fatal: in parameter smtpd_relay_restrictions or smtpd_recipient_restrictions, specify at least one working instance of: reject_unauth_destination, defer_unauth_destination, reject, defer, defer_if_permit or check_relay_domains
```

Setting postfix_smtpd_relay_restrictions to postfix's default value solves the issue:
http://www.postfix.org/postconf.5.html#smtpd_relay_restrictions

Would you accept a PR to defaults and README.md?

**Comment by tersmitten** [comment]
You can use `postfix_compatibility_level`
